### ISSUE TITLE
Not a complaint but a request

### ISSUE THREAD

**Issue by kaisarantonn** [sporkus/smol_mantis#2]
Not a complaint but a request, 
my apologize i dont have expert skills on 3D modelling
but from what i see LDO Orbiter v2 is more famous and the user also a lot.

can you build for orbiter v2 please?

Thank you in advance

**Comment by HuegelMensch** [comment]
do u still need this ? i can do this for u.

**Comment by kaisarantonn** [comment]
> do u still need this ? i can do this for u.

Yes, that would be awesome
And for the left & right fans is it impossible to make using heatset insert and m3 screw?

I feel using m2 self tap screws and held by screw frictions will make it loose at some points especially when we regularly maintenance the toolhead

**Comment by sporkus** [comment]
> > do u still need this ? i can do this for u.
> 
> Yes, that would be awesome And for the left & right fans is it impossible to make using heatset insert and m3 screw?
> 
> I feel using m2 self tap screws and held by screw frictions will make it loose at some points especially when we regularly maintenance the toolhead

the 4010 holes are too small for m3. Dirty bird uses 4512 with m3

**Comment by kaisarantonn** [comment]
> > > do u still need this ? i can do this for u.
> 
> > 
> 
> > Yes, that would be awesome And for the left & right fans is it impossible to make using heatset insert and m3 screw?
> 
> > 
> 
> > I feel using m2 self tap screws and held by screw frictions will make it loose at some points especially when we regularly maintenance the toolhead
> 
> 
> 
> the 4010 holes are too small for m3. Dirty bird uses 4512 with m3

Oh i see, then maybe for V2 orbiter version can you help me?

**Comment by sporkus** [comment]
I'm not gonna do this, but if anyone wants to do a PR i'd be happy to accept.
