### ISSUE TITLE
Fan isnt working

### ISSUE THREAD

**Issue by HuegelMensch** [sporkus/smol_mantis#3]
It seems like the right fan is getting to hot and don't work.
Seems like a know issue for v0.
Can someone proof or denie this ? 
I have this problem on two printers with gdstime Fans.

**Comment by sporkus** [comment]
I personally don't have this issue, but I'm using a delta and don't have a v0.

**Comment by HuegelMensch** [comment]
i myself dont have a v0. but they also use 40mm fans.
Can u may link the deltas ? They are 5V right ?

**Comment by sporkus** [comment]
> i myself dont have a v0. but they also use 40mm fans. Can u may link the deltas ? They are 5V right ?

https://github.com/sporkus/smol_mantis#bom
