### ISSUE TITLE
Longer hotends fan duct feature request

### ISSUE THREAD

**Issue by FedorZa** [sporkus/smol_mantis#4]
Hello! 
Really neat design! but here are definitely lack of longer ducts for longer "volcano-size" hotends (like crazy volcano/rapido)
Basically it's require ducts to be 8mm longer.

**Comment by Teuflor** [comment]
would also be interested in! also need for longer hotends an new carriage mount include euclid probe... 
i would be switch instantly if this will happen

**Comment by kostake2011** [comment]
It would be great. If I could put a chc pro in that toolhead

**Comment by Solders2004** [comment]
This is a very comfortable head, but I can't use it with CHC Pro or Volcano and it makes me very sad. the creator will hear our requests and do something about this problem. thanks

**Comment by Sasha1255** [comment]
It would be wonderful if the author made long blowing nozzles under chc pro, I would immediately start printing and putting this head on.

**Comment by sporkus** [comment]
For Rapido, check out [mantis-Xol](https://github.com/Armchair-Engineering/Mantis-Xol/tree/main/STL). 

There's no way to do CHC because that requires a v6 style body.

Either way, you'll likely be cooling limited with the dual 4010.

**Comment by FedorZa** [comment]
There are lot of options to mount CHC pro on dragon-style heatsinks. 
XOL is over-complicated if you'll ask me :)

Thanks anyway :)
